# base image source https://github.com/rhdt/EL-Dockerfiles/blob/master/base/python3/Dockerfile

FROM prod.registry.devshift.net/osio-prod/base/python3:latest

LABEL maintainer="Sarah Masud <smasud@redhat.com>"

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt && rm /requirements.txt

COPY ./src /src
COPY ./src/config.py.template /src/config.py

ADD ./entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
EXPOSE 6006

ENTRYPOINT ["/bin/entrypoint.sh"]