FROM quay.io/openshiftio/fabric8-analytics-f8a-hpf-insights:latest

LABEL MAINTAINER="Sarah Masud <smasud@redhat.com>"

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./tests/ /tests
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/

RUN pip3 install pytest pytest-cov radon

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
