FROM quay.io/openshiftio/fabric8-analytics-f8a-hpf-insights:latest

LABEL MAINTAINER="Lucky Suman <lsuman@redhat.com>"

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./tests/ /tests
ADD ./tools/ /tools
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
ADD ./.git /.git
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/

RUN pip3 install pytest pytest-cov radon==2.4.0

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
